CREATE TABLE connections (
id INT(20) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
devicea INT (20) UNSIGNED NOT NULL,
deviceb INT (20) UNSIGNED NOT NULL,
FOREIGN KEY (devicea) REFERENCES devices(id)
ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (deviceb) REFERENCES devices(id)
ON DELETE CASCADE ON UPDATE CASCADE
);