CREATE TABLE projects (

	pname VARCHAR(20) PRIMARY KEY,
	powner INT(10) UNSIGNED NOT NULL,
	psnapshot BLOB NOT NULL,
	FOREIGN KEY (powner) REFERENCES users(id)
	ON DELETE CASCADE ON UPDATE CASCADE
);